# Generated by Django 2.2.1 on 2020-04-01 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.ImageField(upload_to='media', verbose_name='第一')),
                ('two', models.ImageField(null=True, upload_to='media', verbose_name='第二')),
                ('three', models.ImageField(null=True, upload_to='media', verbose_name='第三')),
                ('title', models.CharField(max_length=64, verbose_name='活动标题')),
                ('content', models.TextField(verbose_name='活动内容')),
                ('status', models.BooleanField(verbose_name='状态')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sump', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('name', models.CharField(max_length=32, verbose_name='电影名称')),
                ('director', models.CharField(max_length=32, verbose_name='导演名称')),
                ('country', models.CharField(max_length=32, verbose_name='国家')),
                ('years', models.CharField(max_length=32, verbose_name='年份')),
                ('leader', models.CharField(max_length=32, verbose_name='主演')),
                ('d_rate_nums', models.IntegerField(verbose_name='豆瓣评价数')),
                ('d_rate', models.CharField(max_length=32, verbose_name='豆瓣评分')),
                ('intro', models.TextField(verbose_name='描述')),
                ('num', models.IntegerField(default=0, verbose_name='浏览量')),
                ('pic', models.FileField(max_length=64, upload_to='movie_cover', verbose_name='封面图片')),
                ('good', models.CharField(choices=[('奥斯卡', '奥斯卡'), ('戛纳', '戛纳'), ('金鸡', '金鸡'), ('None', 'None')], default=None, max_length=32, verbose_name='获奖')),
            ],
            options={
                'verbose_name': '电影',
                'verbose_name_plural': '电影',
            },
        ),
        migrations.CreateModel(
            name='Num',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.IntegerField(default=0, verbose_name='用户数量')),
                ('movies', models.IntegerField(default=0, verbose_name='电影数量')),
                ('comments', models.IntegerField(default=0, verbose_name='评论数量')),
                ('rates', models.IntegerField(default=0, verbose_name='评分汇总')),
                ('actions', models.IntegerField(default=0, verbose_name='活动汇总')),
                ('message_boards', models.IntegerField(default=0, verbose_name='留言汇总')),
            ],
            options={
                'verbose_name': '数据统计',
                'verbose_name_plural': '数据统计',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='标签')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='账号')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('phone', models.CharField(max_length=32, verbose_name='手机号码')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='名字')),
                ('address', models.CharField(max_length=32, verbose_name='地址')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.FloatField(verbose_name='评分')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Movie', verbose_name='电影id')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '评分信息',
                'verbose_name_plural': '评分信息',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='collect',
            field=models.ManyToManyField(blank=True, to='user.User', verbose_name='收藏者'),
        ),
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(blank=True, to='user.Tags', verbose_name='标签'),
        ),
        migrations.CreateModel(
            name='MessageBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=64, verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('good', models.IntegerField(default=0, verbose_name='点赞')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Movie', verbose_name='电影')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='BoardComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=32, verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('message_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.MessageBoard', verbose_name='留言')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '子留言',
                'verbose_name_plural': '子留言',
            },
        ),
        migrations.CreateModel(
            name='ActionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=64, verbose_name='活动评论')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Action', verbose_name='活动')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户')),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='user',
            field=models.ManyToManyField(blank=True, to='user.User', verbose_name='参加用户'),
        ),
    ]
