# Generated by Django 2.2.1 on 2020-04-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actioncomment',
            name='action',
        ),
        migrations.RemoveField(
            model_name='actioncomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='boardcomment',
            name='message_board',
        ),
        migrations.RemoveField(
            model_name='boardcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='messageboard',
            name='user',
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=128, verbose_name='导演名称'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='电影名称'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='标签'),
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='ActionComment',
        ),
        migrations.DeleteModel(
            name='BoardComment',
        ),
        migrations.DeleteModel(
            name='MessageBoard',
        ),
    ]
