# Generated by Django 2.2.1 on 2020-04-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200416_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='leader',
            field=models.CharField(max_length=128, verbose_name='主演'),
        ),
    ]
